[2024-06-13T05:09:50.165+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: tourism_data_pipeline.save_csv_to_s3 manual__2024-01-01T00:00:00+09:00 [queued]>
[2024-06-13T05:09:50.207+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: tourism_data_pipeline.save_csv_to_s3 manual__2024-01-01T00:00:00+09:00 [queued]>
[2024-06-13T05:09:50.208+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-13T05:09:50.208+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-06-13T05:09:50.208+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-13T05:09:50.261+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): save_csv_to_s3> on 2023-12-31 15:00:00+00:00
[2024-06-13T05:09:50.280+0000] {standard_task_runner.py:55} INFO - Started process 1115 to run task
[2024-06-13T05:09:50.296+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tourism_data_pipeline', 'save_csv_to_s3', 'manual__2024-01-01T00:00:00+09:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/scraping-tourism-API.py', '--cfg-path', '/tmp/tmpikf76r8l']
[2024-06-13T05:09:50.304+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask save_csv_to_s3
[2024-06-13T05:09:51.003+0000] {task_command.py:388} INFO - Running <TaskInstance: tourism_data_pipeline.save_csv_to_s3 manual__2024-01-01T00:00:00+09:00 [running]> on host 557189db82cf
[2024-06-13T05:09:51.151+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sangmin
AIRFLOW_CTX_DAG_ID=tourism_data_pipeline
AIRFLOW_CTX_TASK_ID=save_csv_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-12-31T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-01T00:00:00+09:00
[2024-06-13T05:09:51.153+0000] {logging_mixin.py:137} INFO - Connect S3
[2024-06-13T05:09:51.153+0000] {logging_mixin.py:137} INFO - Done
[2024-06-13T05:09:51.153+0000] {logging_mixin.py:137} INFO - Save csv to s3
[2024-06-13T05:09:51.307+0000] {base.py:73} INFO - Using connection ID 'dev-3-2-bucket' for task execution.
[2024-06-13T05:09:51.308+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='dev-3-2-bucket', conn_type='aws') credentials retrieved from login and password.
[2024-06-13T05:09:54.874+0000] {logging_mixin.py:137} INFO - Done
[2024-06-13T05:09:54.877+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-06-13T05:09:54.910+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=tourism_data_pipeline, task_id=save_csv_to_s3, execution_date=20231231T150000, start_date=20240613T050950, end_date=20240613T050954
[2024-06-13T05:09:55.097+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-06-13T05:09:55.177+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T05:17:31.652+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: tourism_data_pipeline.save_csv_to_s3 manual__2024-01-01T00:00:00+09:00 [queued]>
[2024-06-13T05:17:31.665+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: tourism_data_pipeline.save_csv_to_s3 manual__2024-01-01T00:00:00+09:00 [queued]>
[2024-06-13T05:17:31.666+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-13T05:17:31.666+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-06-13T05:17:31.666+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-13T05:17:31.680+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): save_csv_to_s3> on 2023-12-31 15:00:00+00:00
[2024-06-13T05:17:31.689+0000] {standard_task_runner.py:55} INFO - Started process 1409 to run task
[2024-06-13T05:17:31.694+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tourism_data_pipeline', 'save_csv_to_s3', 'manual__2024-01-01T00:00:00+09:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/scraping-tourism-API.py', '--cfg-path', '/tmp/tmp16d5_qmm']
[2024-06-13T05:17:31.698+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask save_csv_to_s3
[2024-06-13T05:17:32.072+0000] {task_command.py:388} INFO - Running <TaskInstance: tourism_data_pipeline.save_csv_to_s3 manual__2024-01-01T00:00:00+09:00 [running]> on host 557189db82cf
[2024-06-13T05:17:32.141+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sangmin
AIRFLOW_CTX_DAG_ID=tourism_data_pipeline
AIRFLOW_CTX_TASK_ID=save_csv_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-12-31T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-01T00:00:00+09:00
[2024-06-13T05:17:32.142+0000] {logging_mixin.py:137} INFO - Connect S3
[2024-06-13T05:17:32.143+0000] {logging_mixin.py:137} INFO - Done
[2024-06-13T05:17:32.143+0000] {logging_mixin.py:137} INFO - Save csv to s3
[2024-06-13T05:17:32.194+0000] {base.py:73} INFO - Using connection ID 'dev-3-2-bucket' for task execution.
[2024-06-13T05:17:32.196+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='dev-3-2-bucket', conn_type='aws') credentials retrieved from login and password.
[2024-06-13T05:17:33.683+0000] {logging_mixin.py:137} INFO - Done
[2024-06-13T05:17:33.685+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-06-13T05:17:33.713+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=tourism_data_pipeline, task_id=save_csv_to_s3, execution_date=20231231T150000, start_date=20240613T051731, end_date=20240613T051733
[2024-06-13T05:17:33.776+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-06-13T05:17:33.821+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T05:38:04.885+0000] {taskinstance.py:1073} INFO - Dependencies not met for <TaskInstance: tourism_data_pipeline.save_csv_to_s3 manual__2024-01-01T00:00:00+09:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-06-13T05:38:04.923+0000] {local_task_job.py:147} INFO - Task is not able to be run
